version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - export BUCKET=s3lockstate
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml  
