--- 
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources: 
  LambdaFunction:
    Type: "AWS::Serverless::Function" 
    Properties: 
      CodeUri: ./
      FunctionName: "helloworld"
      Handler: "index.handler"
      Runtime: "python3.8"
    
