--- 
AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties: 
      Code: 
        ZipFile: |
          import json
          def lambda_handler(event, context):
              # TODO implement
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from Lambda!')
                }
      FunctionName: "hello_func"
      Handler: "index.handler"
      Role: "arn:aws:iam::020046395185:role/AWSCloudFormationStackSetAdministrationRole"
      Runtime: "python3.8"
